# Generated by Django 4.2.5 on 2023-12-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('datanascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('passaporte', models.CharField(blank=True, max_length=255, null=True, verbose_name='Passaporte')),
                ('datavalidade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('contato', models.PositiveIntegerField(blank=True, null=True, verbose_name='Contato')),
                ('cpfcnpj', models.CharField(blank=True, max_length=400, null=True, verbose_name='CPF ou CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Endereço')),
                ('email', models.CharField(blank=True, max_length=400, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Denúncia')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('timestamp', models.DateTimeField(verbose_name='Data e Hora(formato: (ex.:22/10/2019 12:31:00) )')),
                ('description', models.TextField(max_length=400, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Viagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destino')),
                ('dataida', models.DateField(blank=True, null=True, verbose_name='Data da ida')),
                ('datavolta', models.DateField(blank=True, null=True, verbose_name='Data da Volta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_exemplo.clientes')),
            ],
        ),
    ]
